# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 17:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=30)),
                ('recept', models.TextField()),
                ('poreklo', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vrsta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(choices=[('glavna', 'glavna'), ('sladica', 'sladica'), ('predjed', 'predjed')], max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='jed',
            name='vrsta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svincnik.Vrsta'),
        ),
    ]
