# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 15:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('svincnik', '0002_auto_20160421_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zapis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vsebina', models.TextField()),
                ('objavljeno', models.DateTimeField()),
                ('jed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svincnik.Jed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zapisi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Zapisi',
            },
        ),
    ]
