# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svincnik', '0003_zapis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jed',
            name='vrsta',
            field=models.CharField(choices=[(1, 'glavna'), (2, 'sladica'), (3, 'predjed')], max_length=30),
        ),
        migrations.AlterField(
            model_name='zapis',
            name='jed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zapisi', to='svincnik.Jed'),
        ),
        migrations.AlterField(
            model_name='zapis',
            name='objavljeno',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
